remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: CartoonHolden28_500.jpg
title: Deep Earth Doctoral School
subtitle: Les Houches, France <br> Oct. 24, 2022 - Nov. 4, 2022
date: Oct. 24, 2022 - Nov. 4, 2022
