remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: /assets/images/Affiche2.png
title: Solid Earth Doctoral School
subtitle: Les Houches, France 
date: Oct. 16, 2023 - Oct. 27, 2023
